############################
## CHANGE THESE
############################

baseURL: 'https://chrede88.github.io/quit-pub'
title: quit-pub

############################
## MISC
############################

enableEmoji: true
disableKinds: ['taxonomy', 'term']
languageCode: 'en-us'


