############################
## Navbar
############################

main:
- name: Home
  url: /
  weight: 10
- name: Publications
  url: /publications/
  weight: 20
- name: About
  url: /about/
  weight: 30